language: python
python:
    - 3.7

os: linux

dist : ubuntu

cache: pip
        
branches:
    - master

env:
    jobs:
        - PLATFORMIO_CI_SRC=examples/configureStepperMotor
        - PLATFORMIO_CI_SRC=examples/testStepperMotor

install:
    - pip install -U platformio
    - platformio platform install -f infineonxmc 
    - platformio platform install -f atmelavr

script:
    - platformio ci --lib="." --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno
